from setuptools import setup, find_packages

setup(
    name="quantum_mechanics_interactive",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "matplotlib>=3.4.0",
        "PyQt6>=6.2.0",
        "sympy>=1.8.0",
        "pytest>=6.2.0",
        "pyyaml>=5.4.0",
        "ipython>=7.0.0",
        "jupyter>=1.0.0",
        "networkx>=2.6.0",
        "torch>=1.9.0",
        "pandas>=1.3.0",
        "plotly>=5.1.0",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="An interactive educational software for quantum mechanics",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/quantum_mechanics_interactive",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.8",
)
